# Generated by Django 6.0.2 on 2026-02-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم البطاقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('installment', 'قسط')], max_length=15, verbose_name='طريقة الدفع')),
                ('payment_location', models.CharField(choices=[('in_person', 'حضوري'), ('remote', 'عن بعد')], default='in_person', max_length=10, verbose_name='مكان الدفع')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة القسط')),
                ('paid_installments', models.PositiveIntegerField(default=0, verbose_name='الأقساط المدفوعة')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب البنكي (للتحويل)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة/الدبلومة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-registration_date'],
            },
        ),
    ]
