# Generated by Django 5.2.11 on 2026-03-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات البريد')),
                ('email_host', models.CharField(blank=True, max_length=255, verbose_name='خادم البريد (SMTP)')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='منفذ البريد')),
                ('email_host_user', models.CharField(blank=True, max_length=255, verbose_name='اسم مستخدم البريد')),
                ('email_host_password', models.CharField(blank=True, max_length=255, verbose_name='كلمة مرور البريد')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='استخدام TLS')),
                ('email_from_address', models.EmailField(blank=True, max_length=254, verbose_name='عنوان المرسل')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات واتساب')),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=500, verbose_name='مفتاح API واتساب')),
                ('whatsapp_api_url', models.URLField(blank=True, default='https://api.ultramsg.com/instance{instance_id}/messages/chat', verbose_name='رابط API واتساب')),
                ('whatsapp_instance_id', models.CharField(blank=True, max_length=50, verbose_name='معرف Instance')),
                ('reminder_2days_template', models.TextField(default='مرحباً {student_name}،\n\nنذكركم بأن القسط رقم {installment_number} بمبلغ {amount} ريال مستحق بعد يومين بتاريخ {due_date}.\n\nشكراً لاختياركم معهدنا.', verbose_name='قالب تذكير قبل يومين')),
                ('reminder_1day_template', models.TextField(default='مرحباً {student_name}،\n\nنذكركم بأن القسط رقم {installment_number} بمبلغ {amount} ريال مستحق غداً بتاريخ {due_date}.\n\nشكراً لاختياركم معهدنا.', verbose_name='قالب تذكير قبل يوم')),
                ('reminder_due_template', models.TextField(default='مرحباً {student_name}،\n\nنذكركم بأن القسط رقم {installment_number} بمبلغ {amount} ريال مستحق اليوم بتاريخ {due_date}.\n\nيرجى السداد في أقرب وقت ممكن.\n\nشكراً لكم.', verbose_name='قالب تذكير يوم الاستحقاق')),
                ('overdue_template', models.TextField(default='مرحباً {student_name}،\n\nنفيدكم بأن القسط رقم {installment_number} بمبلغ {amount} ريال قد تجاوز تاريخ الاستحقاق بتاريخ {due_date} ولم يتم السداد حتى الآن.\n\nعدد أيام التأخر: {overdue_days} يوم\n\nيرجى السداد فوراً لتجنب أي إجراءات إضافية.\n\nللاستفسار: {contact_phone}', verbose_name='قالب إشعار التأخر')),
                ('reminder_2days_before', models.BooleanField(default=True, verbose_name='إرسال تذكير قبل يومين')),
                ('reminder_1day_before', models.BooleanField(default=True, verbose_name='إرسال تذكير قبل يوم')),
                ('reminder_on_due_date', models.BooleanField(default=True, verbose_name='إرسال تذكير يوم الاستحقاق')),
                ('send_overdue_notice', models.BooleanField(default=True, verbose_name='إرسال إشعار التأخر')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم التواصل للاستفسار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='first_installment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ أول قسط'),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة القسط')),
                ('first_installment_date', models.DateField(verbose_name='تاريخ أول قسط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'خطة تقسيط',
                'verbose_name_plural': 'خطط التقسيط',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('reminder_sent_2days', models.BooleanField(default=False, verbose_name='تم إرسال تذكير قبل يومين')),
                ('reminder_sent_1day', models.BooleanField(default=False, verbose_name='تم إرسال تذكير قبل يوم')),
                ('reminder_sent_due', models.BooleanField(default=False, verbose_name='تم إرسال تذكير يوم الاستحقاق')),
                ('overdue_notice_sent', models.BooleanField(default=False, verbose_name='تم إرسال إشعار التأخر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.installmentplan', verbose_name='خطة التقسيط')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('sms', 'رسالة نصية')], max_length=10, verbose_name='نوع الإشعار')),
                ('notification_reason', models.CharField(max_length=50, verbose_name='سبب الإشعار')),
                ('recipient', models.CharField(max_length=255, verbose_name='المستلم')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='محتوى الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], default='pending', max_length=10, verbose_name='الحالة')),
                ('response_data', models.TextField(blank=True, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.installment', verbose_name='القسط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجل الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
