# Generated by Django 5.2.11 on 2026-03-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_type'),
        ('students', '0002_notificationsettings_student_first_installment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة/الدبلوما'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_method',
            field=models.CharField(choices=[('full', 'دفعة واحدة'), ('installment', 'قسط')], max_length=15, verbose_name='طريقة الدفع'),
        ),
    ]
