# Generated by Django 5.2.11 on 2026-03-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_course_alter_student_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_location',
        ),
    ]
