# Generated by Django 5.2.11 on 2026-03-16 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_remove_branch_monthly_target_and_more'),
        ('courses', '0002_alter_course_course_type'),
        ('students', '0004_remove_student_payment_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('new', 'تسجيل جديد'), ('improvement', 'تقوية'), ('repeat', 'إعادة')], default='new', max_length=15, verbose_name='نوع التسجيل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('withdrawn', 'منسحب'), ('suspended', 'معلق')], default='active', max_length=15, verbose_name='حالة التسجيل')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('payment_method', models.CharField(choices=[('full', 'دفعة واحدة'), ('installment', 'قسط')], max_length=15, verbose_name='طريقة الدفع')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة القسط')),
                ('first_installment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ أول قسط')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('withdrawal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانسحاب')),
                ('withdrawal_reason', models.TextField(blank=True, verbose_name='سبب الانسحاب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة/الدبلومة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل دورة',
                'verbose_name_plural': 'تسجيلات الدورات',
                'ordering': ['-enrollment_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'course', 'status'), name='unique_active_enrollment')],
            },
        ),
    ]
