# Generated by Django 5.2.11 on 2026-03-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='whatsapp_api_key',
        ),
    ]
