# Generated by Django 5.2.11 on 2026-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0002_alter_branch_options_remove_branch_monthly_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_branches',
            field=models.ManyToManyField(blank=True, related_name='regional_managers', to='branches.branch', verbose_name='الفروع التي يديرها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('branch_manager', 'مدير فرع'), ('employee', 'موظف'), ('regional_manager', 'مدير إقليمي'), ('accountant', 'محاسب')], default='employee', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
