# Generated by Django 5.2.11 on 2026-02-27 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='monthly_target',
        ),
        migrations.CreateModel(
            name='BranchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('month', models.PositiveIntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المستهدف')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'هدف الفرع',
                'verbose_name_plural': 'أهداف الفروع',
                'unique_together': {('branch', 'year', 'month')},
            },
        ),
    ]
