# Generated by Django 6.0.2 on 2026-02-27 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('category', models.CharField(choices=[('salaries', 'رواتب'), ('rent', 'إيجار'), ('utilities', 'مرافق (كهرباء، مياه، إنترنت)'), ('supplies', 'مستلزمات'), ('marketing', 'تسويق'), ('maintenance', 'صيانة'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال/الفاتورة')),
                ('receipt_image', models.ImageField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='صورة الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الصرف بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('income_type', models.CharField(choices=[('registration', 'تسجيل جديد'), ('installment', 'تحصيل قسط')], max_length=15, verbose_name='نوع الإيراد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('visa', 'فيزا'), ('bank_transfer', 'تحويل بنكي')], max_length=15, verbose_name='طريقة الدفع')),
                ('payment_location', models.CharField(choices=[('in_person', 'حضوري'), ('remote', 'عن بعد')], max_length=10, verbose_name='مكان الدفع')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب البنكي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حصل بواسطة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة/الدبلومة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إيراد',
                'verbose_name_plural': 'الإيرادات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_registration_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيرادات التسجيل')),
                ('total_installment_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيرادات التحصيل')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافي')),
                ('daily_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الهدف اليومي')),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الإنجاز %')),
                ('new_registrations_count', models.PositiveIntegerField(default=0, verbose_name='عدد التسجيلات الجديدة')),
                ('installments_collected_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأقساط المحصلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'ملخص يومي',
                'verbose_name_plural': 'الملخصات اليومية',
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
