# Generated by Django 5.2.11 on 2026-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'مدى'), ('visa', 'فيزا'), ('bank_transfer', 'تحويل بنكي')], max_length=15, verbose_name='طريقة الدفع'),
        ),
    ]
