# Generated by Django 5.2.11 on 2026-03-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_payment_location'),
        ('transactions', '0003_alter_income_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.installment', verbose_name='القسط المرتبط'),
        ),
    ]
