# Generated by Django 5.2.11 on 2026-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_income_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي'),
        ),
    ]
