# Generated by Django 6.0.2 on 2026-02-27 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('daily_registrations', models.PositiveIntegerField(default=0, verbose_name='التسجيلات اليومية')),
                ('daily_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإيراد اليومي')),
                ('monthly_registrations', models.PositiveIntegerField(default=0, verbose_name='التسجيلات الشهرية')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإيراد الشهري')),
                ('total_registrations', models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='الدورة/الدبلومة')),
            ],
            options={
                'verbose_name': 'تقرير دورة',
                'verbose_name_plural': 'تقارير الدورات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('registrations_count', models.PositiveIntegerField(default=0, verbose_name='عدد التسجيلات')),
                ('installments_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحصيلات')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المحصل')),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='كاش')),
                ('visa_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='فيزا')),
                ('bank_transfer_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تحويل بنكي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تقرير موظف',
                'verbose_name_plural': 'تقارير الموظفين',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('monthly_target', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الهدف الشهري')),
                ('total_registration_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيرادات التسجيل')),
                ('total_installment_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيرادات التحصيل')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيرادات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافي')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الربح')),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الإنجاز %')),
                ('new_students_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب الجدد')),
                ('total_students_count', models.PositiveIntegerField(default=0, verbose_name='إجمالي عدد الطلاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'تقرير شهري',
                'verbose_name_plural': 'التقارير الشهرية',
                'ordering': ['-year', '-month'],
                'unique_together': {('branch', 'year', 'month')},
            },
        ),
    ]
