# Generated by Django 6.0.2 on 2026-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدورة/الدبلومة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدورة')),
                ('course_type', models.CharField(choices=[('diploma', 'دبلومة'), ('course', 'دورة')], max_length=10, verbose_name='النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='المدة (بالأيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branches', models.ManyToManyField(related_name='courses', to='branches.branch', verbose_name='الفروع المتاحة')),
            ],
            options={
                'verbose_name': 'دورة/دبلومة',
                'verbose_name_plural': 'الدورات والدبلومات',
                'ordering': ['-created_at'],
            },
        ),
    ]
