# Generated by Django 5.2.11 on 2026-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('diploma', 'دبلوم'), ('course', 'دورة')], max_length=10, verbose_name='النوع'),
        ),
    ]
