name: Deploy m3had-system

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/ElmashahedBackend
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            # لا داعي لـ migrate هنا لأنك ترفع قاعدة جاهزة، لكن يفضل لضمان التوافق
            python manage.py migrate
            python manage.py collectstatic --noinput
            
            # أهم سطرين لضمان عمل اللوجن بعد رفع القاعدة الجديدة
            sudo chown www-data:www-data db.sqlite3
            sudo chmod 664 db.sqlite3
            
            sudo systemctl restart gunicorn_mashahed